### ISSUE TITLE
Update on unmounted component

### ISSUE THREAD

**Issue by Gaia-Nutrition** [promptworks/formik-apollo#1]
Within my asynchronous `onSubmit` callback (or even within the `onCompleted` callback provided by `useMutation`) it is impossible to do anything that un-mounts Formik (like navigating) since the `form.setSubmitting(false);` is only called after `onSubmit` completes. https://github.com/promptworks/formik-apollo/blob/8c8a8e1e21969aa9cfa1a34fae0f5c71db09d016/src/useSubmit.ts#L21-L23

The two workarounds I've found:
1. use `setImmediate` (dirty solution):
```js
setImmediate(() => history.push('/somethingelse'));
```
2. write a wrapper function that executes the callback returned from `useSubmit` and navigates after that completes. (quite complex)
```js
const submitForm = useSubmit((data: SomeType) => mutate({
  variables: {
    input: data,
  }
}));

const handleSubmit = useCallback(
  async (data: SomeType, form: FormikHelpers<SomeType>) => {
    const mutationResult: SomeMutationResult | null | undefined = await submitForm(data, form);
    if (mutationResult && mutationResult.id) {
      history.push(`/entities/${mutationResult.id}`);
    }
  },
  [history, submitForm],
);
```
How are you solving this problem?

**Comment by rzane** [comment]
So far, I've been doing solution #2, but you're right that it's not very ergonomic.

Maybe `useSubmit` could accept an `onCompleted` callback? We'd just call it after the final `setSubmitting` call.

Would you be open to submitting a PR? Also, I should probably add some documentation 😉
