### ISSUE TITLE
passing the GraphQL result to getErrors?

### ISSUE THREAD

**Issue by dmcclory** [promptworks/formik-apollo#3]
Hello! Cool project! 😉

I have an api that I can't really modify, which gives me back error messages in the result body in a slightly different format than what this library is looking for. I'd like to be able to pass in a custom method which can pluck the error codes from the right field.

I see that you can pass a `getErrors` method to useSubmit (which defaults to getValidationErrors). That gets me partway there, but it only passes the error object. 

Could we rearrange it so that that the result - if it it exists - is passed as a second optional argument?

The changes would be something like:

```
+      let result
       try {
-        const result = await mutate(values, form);
+        result = await mutate(values, form);
         form.setSubmitting(false);
         await onCompleted(result, values, form);
         return result;
       } catch (error) {
+        let resultMaybe = (typeof result !== 'undefined') ? result : null
         if (isApolloError(error)) {
           form.setStatus(getStatus(error));
-          form.setErrors(getErrors(error) as any);
+          form.setErrors(getErrors(error, resultMaybe) as any);
           form.setSubmitting(false);
           await onError(error, values, form);
           ...
```

**Comment by rzane** [comment]
With this change, `result` would always be `undefined` since `mutate` threw an error.

You should be able to customize the error messages by implementing your own `getErrors` function and passing it in. In your `getErrors` function, you can extract the errors from `error.graphQLErrors`.
